[theme]
primaryColor="#b91c1c"            # Tekkadan Crimson Red
backgroundColor="#0b0c0e"         # Hangar Dark Background
secondaryBackgroundColor="#111318" # Gunmetal Armor Grey
textColor="#d1d5db"               # High-contrast Silver
font="monospace"